<?php

namespace Acme\GeekBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * squareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class squareRepository extends EntityRepository
{
}
